// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate(arg1:number,arg2:number,arg3:string):Promise<number>;

export function ClearHistory():Promise<void>;

export function GetHistory():Promise<Array<string>>;
