// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Calculate'](arg1, arg2, arg3);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}
